# Generated by Django 5.2.5 on 2025-08-14 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EggRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('crates', models.PositiveIntegerField()),
                ('pieces', models.PositiveIntegerField(default=0)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('animal_category', models.CharField(choices=[('laying_bird', 'Laying Bird'), ('young_layer', 'Young Layer'), ('cow', 'Cow'), ('goat', 'Goat'), ('pig', 'Pig')], max_length=20)),
                ('quantity', models.FloatField(help_text='Bags for birds, Kg for others')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SaleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('product', models.CharField(choices=[('egg', 'Egg'), ('milk', 'Milk'), ('meat', 'Meat'), ('other', 'Other')], max_length=20)),
                ('crates', models.PositiveIntegerField(default=0)),
                ('pieces', models.PositiveIntegerField(default=0)),
                ('quantity', models.FloatField(default=0, help_text='Kg or units for non-egg products')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
