# Generated by Django 5.2.5 on 2025-08-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_eggrecord_feedrecord_salerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('vaccine', 'Vaccine'), ('repair', 'Repair'), ('transportation', 'Transportation'), ('other', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_category', models.CharField(choices=[('laying_bird', 'Laying Bird'), ('young_layer', 'Young Layer'), ('cow', 'Cow'), ('goat', 'Goat'), ('pig', 'Pig')], max_length=20)),
                ('quantity_bags', models.PositiveIntegerField()),
                ('price_per_bag', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
