# Generated by Django 5.2.5 on 2025-08-14 12:08

import records.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_expense_feedpurchase'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', records.models.CustomUserManager()),
            ],
        ),
    ]
