# Generated by Django 5.2.5 on 2025-08-14 12:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='salerecord',
            name='price_per_crate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
