# Generated by Django 5.2.5 on 2025-08-14 12:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_salerecord_price_per_crate'),
    ]

    operations = [
        migrations.AddField(
            model_name='salerecord',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
