# Generated by Django 5.2.5 on 2025-08-31 18:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_salerecord_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedpurchase',
            name='quantity_bags',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='feedrecord',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Bags for birds, Kg for others', max_digits=10),
        ),
        migrations.AlterField(
            model_name='salerecord',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Kg or units for non-egg products', max_digits=10),
        ),
    ]
